# Generated by Django 4.2.5 on 2023-09-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_variation_created_at'),
        ('cart_app', '0002_cartitem_is_active_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='product_app.variation'),
        ),
    ]
