# Generated by Django 4.2.5 on 2023-09-14 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0006_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
